/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Negocios.cargarempleados;
import Negocios.cargarsucursales;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PXNDX
 */
public class nomina extends javax.swing.JFrame {

    /**
     * Creates new form nomina
     */
    public nomina() {
        initComponents();
        CargarDatos();
    }
    private  void CargarDatos ()
    {
        cargarsucursales Cargar =new  cargarsucursales();
        ArrayList<cargarsucursales> Lista=new ArrayList();
        Lista = Cargar.cargarsucursales();
         int i = 0;
            for (cargarsucursales  X:Lista  ) 
             {
                this.Com_sucursales.addItem(X);   
                i++;
             }
    }
        private  void Cargarempleados ()
    {
        cargarempleados Cargar =new  cargarempleados();
        ArrayList<cargarempleados> Lista=new ArrayList();
        Lista = Cargar.cargarempleados();
         int i = 0;
            for (cargarempleados  X:Lista  ) 
             {
                this.Com_empleado.addItem(X);   
                i++;
             }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Cerrar6 = new jcMousePanel.jcMousePanel();
        Minimizar = new jcMousePanel.jcMousePanel();
        Cerrar = new jcMousePanel.jcMousePanel();
        Cerrar7 = new jcMousePanel.jcMousePanel();
        JPanel_Contratacion = new javax.swing.JPanel();
        JPanel_ProcesoSeleccion = new jcMousePanel.jcMousePanel();
        SetErrorNotaEntre = new javax.swing.JLabel();
        Com_sucursales = new javax.swing.JComboBox();
        Label4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        Ingresar = new javax.swing.JRadioButton();
        JPanel_Aspirante = new jcMousePanel.jcMousePanel();
        DatosPersonales2 = new javax.swing.JPanel();
        DatosPersonales3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SetErrorTelefono = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        SetErrorCelular = new javax.swing.JLabel();
        Txt_Telefono1 = new javax.swing.JFormattedTextField();
        Txt_TelefonoCelular1 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        Txt_Identificacion1 = new javax.swing.JFormattedTextField();
        SetErrorCedula = new javax.swing.JLabel();
        Txt_Apellido = new javax.swing.JTextField();
        SetErrorApellido = new javax.swing.JLabel();
        SetErrorNombre = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Direccion = new javax.swing.JTextField();
        SetErrorDireccion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Txt_Direccion1 = new javax.swing.JTextField();
        SetErrorCiudad1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Txt_Correo = new javax.swing.JTextField();
        SetErrorCorreo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Com_empleado = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        Btn_Modificar = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Contrato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/Fondos/bgImage.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setOpaque(false);

        Cerrar6.setToolTipText("Ayuda");
        Cerrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/faq.png"))); // NOI18N
        Cerrar6.setVisibleLogo(false);
        Cerrar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cerrar6Layout = new javax.swing.GroupLayout(Cerrar6);
        Cerrar6.setLayout(Cerrar6Layout);
        Cerrar6Layout.setHorizontalGroup(
            Cerrar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Cerrar6Layout.setVerticalGroup(
            Cerrar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Minimizar.setToolTipText("Minimizar");
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/download.png"))); // NOI18N
        Minimizar.setVisibleLogo(false);
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MinimizarLayout = new javax.swing.GroupLayout(Minimizar);
        Minimizar.setLayout(MinimizarLayout);
        MinimizarLayout.setHorizontalGroup(
            MinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        MinimizarLayout.setVerticalGroup(
            MinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Cerrar.setToolTipText("Cerrar");
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/delete.png"))); // NOI18N
        Cerrar.setVisibleLogo(false);
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        Cerrar7.setToolTipText("Atras");
        Cerrar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/send-user.png"))); // NOI18N
        Cerrar7.setVisibleLogo(false);
        Cerrar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cerrar7Layout = new javax.swing.GroupLayout(Cerrar7);
        Cerrar7.setLayout(Cerrar7Layout);
        Cerrar7Layout.setHorizontalGroup(
            Cerrar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Cerrar7Layout.setVerticalGroup(
            Cerrar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(Cerrar7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cerrar6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cerrar7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(340, 0, 130, 30);

        JPanel_Contratacion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JPanel_Contratacion.setForeground(new java.awt.Color(255, 255, 255));
        JPanel_Contratacion.setOpaque(false);
        JPanel_Contratacion.setLayout(null);

        JPanel_ProcesoSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nomina empresarial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 18), java.awt.Color.white)); // NOI18N
        JPanel_ProcesoSeleccion.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/128/64/notes.png"))); // NOI18N
        JPanel_ProcesoSeleccion.setModo(2);
        JPanel_ProcesoSeleccion.setOpaque(false);
        JPanel_ProcesoSeleccion.setVisibleLogo(false);
        JPanel_ProcesoSeleccion.setLayout(null);

        SetErrorNotaEntre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorNotaEntre.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorNotaEntre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        JPanel_ProcesoSeleccion.add(SetErrorNotaEntre);
        SetErrorNotaEntre.setBounds(310, 40, 16, 20);

        Com_sucursales.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Com_sucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Com_sucursalesActionPerformed(evt);
            }
        });
        JPanel_ProcesoSeleccion.add(Com_sucursales);
        Com_sucursales.setBounds(100, 40, 197, 23);

        Label4.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setText("Sucursal:");
        JPanel_ProcesoSeleccion.add(Label4);
        Label4.setBounds(30, 40, 50, 20);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Estado nomina");
        jCheckBox1.setOpaque(false);
        JPanel_ProcesoSeleccion.add(jCheckBox1);
        jCheckBox1.setBounds(30, 80, 95, 23);

        Ingresar.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("buscar");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresar.setOpaque(false);
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
        });
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        JPanel_ProcesoSeleccion.add(Ingresar);
        Ingresar.setBounds(130, 80, 110, 25);

        JPanel_Contratacion.add(JPanel_ProcesoSeleccion);
        JPanel_ProcesoSeleccion.setBounds(10, 10, 420, 130);

        JPanel_Aspirante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nomina personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 18), java.awt.Color.white)); // NOI18N
        JPanel_Aspirante.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/128/64/notes.png"))); // NOI18N
        JPanel_Aspirante.setModo(2);
        JPanel_Aspirante.setOpaque(false);
        JPanel_Aspirante.setVisibleLogo(false);
        JPanel_Aspirante.setLayout(null);

        DatosPersonales2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos devengados y deducidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 14), java.awt.Color.white)); // NOI18N
        DatosPersonales2.setForeground(new java.awt.Color(255, 255, 255));
        DatosPersonales2.setOpaque(false);

        DatosPersonales3.setForeground(new java.awt.Color(255, 255, 255));
        DatosPersonales3.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Comiciones:");

        SetErrorTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorTelefono.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorTelefono.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bonificaciones:");

        SetErrorCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorCelular.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorCelular.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Txt_Telefono1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        Txt_Telefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Telefono1ActionPerformed(evt);
            }
        });

        Txt_TelefonoCelular1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        Txt_TelefonoCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoCelular1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Horas extra");

        Txt_Identificacion1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        Txt_Identificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Identificacion1ActionPerformed(evt);
            }
        });

        SetErrorCedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorCedula.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorCedula.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Txt_Apellido.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Txt_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ApellidoActionPerformed(evt);
            }
        });
        Txt_Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_ApellidoKeyPressed(evt);
            }
        });

        SetErrorApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorApellido.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorApellido.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        SetErrorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorNombre.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SetErrorNombre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Txt_Nombre.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Txt_Nombre.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                Txt_NombreComponentAdded(evt);
            }
        });
        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        Txt_Nombre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Txt_NombrePropertyChange(evt);
            }
        });
        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sueldo:");

        jLabel5.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dias travagados:");

        Txt_Direccion.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DireccionActionPerformed(evt);
            }
        });

        SetErrorDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorDireccion.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorDireccion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel8.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fondo:");

        jLabel11.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Prestamos:");

        Txt_Direccion1.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Txt_Direccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Direccion1ActionPerformed(evt);
            }
        });

        SetErrorCiudad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorCiudad1.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorCiudad1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel12.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Otros:");

        Txt_Correo.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CorreoActionPerformed(evt);
            }
        });

        SetErrorCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/comment.png"))); // NOI18N
        SetErrorCorreo.setToolTipText("Ingrese el Nombre del Aspirante ");
        SetErrorCorreo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout DatosPersonales3Layout = new javax.swing.GroupLayout(DatosPersonales3);
        DatosPersonales3.setLayout(DatosPersonales3Layout);
        DatosPersonales3Layout.setHorizontalGroup(
            DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonales3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales3Layout.createSequentialGroup()
                        .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_Identificacion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SetErrorApellido)
                            .addComponent(SetErrorNombre)
                            .addComponent(SetErrorCedula)))
                    .addGroup(DatosPersonales3Layout.createSequentialGroup()
                        .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_Direccion)
                            .addComponent(Txt_Telefono1)
                            .addComponent(Txt_TelefonoCelular1)
                            .addComponent(Txt_Direccion1)
                            .addComponent(Txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SetErrorTelefono)
                            .addComponent(SetErrorCelular)
                            .addComponent(SetErrorDireccion)
                            .addComponent(SetErrorCiudad1)
                            .addComponent(SetErrorCorreo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosPersonales3Layout.setVerticalGroup(
            DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonales3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(SetErrorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetErrorApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(SetErrorCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SetErrorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetErrorCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_TelefonoCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(SetErrorDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetErrorCiudad1)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(SetErrorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Empleado:");

        Com_empleado.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Com_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Com_empleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosPersonales2Layout = new javax.swing.GroupLayout(DatosPersonales2);
        DatosPersonales2.setLayout(DatosPersonales2Layout);
        DatosPersonales2Layout.setHorizontalGroup(
            DatosPersonales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPersonales2Layout.createSequentialGroup()
                .addGroup(DatosPersonales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosPersonales2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addComponent(Com_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosPersonales2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DatosPersonales3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        DatosPersonales2Layout.setVerticalGroup(
            DatosPersonales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosPersonales2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosPersonales2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Com_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatosPersonales3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JPanel_Aspirante.add(DatosPersonales2);
        DatosPersonales2.setBounds(20, 40, 330, 340);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Calligraphy", 0, 12), java.awt.Color.white)); // NOI18N
        jPanel7.setOpaque(false);

        Btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/setting.png"))); // NOI18N
        Btn_Modificar.setToolTipText("Actualizar");
        Btn_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });

        Btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/save.png"))); // NOI18N
        Btn_Guardar.setToolTipText("Guadar");
        Btn_Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/notes.png"))); // NOI18N
        Btn_Nuevo.setToolTipText("Limpiar");
        Btn_Nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Contrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/edit-notes.png"))); // NOI18N
        Btn_Contrato.setToolTipText("Limpiar");
        Btn_Contrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Contrato, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        JPanel_Aspirante.add(jPanel7);
        jPanel7.setBounds(90, 390, 220, 70);

        JPanel_Contratacion.add(JPanel_Aspirante);
        JPanel_Aspirante.setBounds(30, 150, 370, 470);

        jPanel3.add(JPanel_Contratacion);
        JPanel_Contratacion.setBounds(20, 60, 440, 640);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/user.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 20, 30, 30);

        jcMousePanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 470, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Cerrar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar6MouseClicked
//        NiconEvent Mensaje=new NiconEvent("Menu de aYuda","Se a precentado un error al cargar los componetes de ayuda por favor espere unos momento",NiconEvent.NOTIFY_ERROR,0,0);
//        NotifyFactory.showDesktopNotify(Mensaje);

        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar6MouseClicked
    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMouseClicked
    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseClicked
    private void Cerrar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar7MouseClicked
//        ServiciosHumanos serHuma = new ServiciosHumanos();
//        serHuma.setVisible(true);
//        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar7MouseClicked
    private void Txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_DireccionActionPerformed
    private void Txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CorreoActionPerformed
    private void Txt_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ApellidoActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidoActionPerformed
    private void Txt_ApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_ApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ApellidoKeyPressed
    private void Txt_NombreComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Txt_NombreComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreComponentAdded
    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed
    private void Txt_NombrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Txt_NombrePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombrePropertyChange
    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreKeyPressed
    private void Txt_Identificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Identificacion1ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Identificacion1ActionPerformed
    private void Txt_Telefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Telefono1ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Telefono1ActionPerformed
    private void Txt_TelefonoCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoCelular1ActionPerformed
    private void Com_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Com_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Com_empleadoActionPerformed
    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        if (("".equals(Txt_Nombre.getText())))
        {
            getToolkit().beep();
            SetErrorNombre.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
////            SetErrorNota.setVisible(false);
////            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Nombre del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
////            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Apellido.getText()))
        {
            getToolkit().beep();
            SetErrorApellido.setVisible(true);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Apellido del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Identificacion1.getText()))
        {
            getToolkit().beep();
            SetErrorCedula.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Identificación del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Telefono1.getText()))
        {
            getToolkit().beep();
            SetErrorTelefono.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Telefono del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }
        else if   ("".equals(Txt_TelefonoCelular1.getText()))
        {
            getToolkit().beep();
            SetErrorCelular.setVisible(false);
            SetErrorTelefono.setVisible(true);
            SetErrorApellido.setVisible(true);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Telefono Celular del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }
        else if   ("".equals(Txt_Direccion.getText()))
        {
            getToolkit().beep();
            SetErrorDireccion.setVisible(true);
            SetErrorCelular.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
//        }else if   ("--Seleccionar---".equals(Com_Ciudad.getSelectedItem()))
//        {
//            getToolkit().beep();
//            SetErrorDireccion.setVisible(false);
//            SetErrorCelular.setVisible(false);
//            SetErrorTelefono.setVisible(false);
//            SetErrorApellido.setVisible(false);
//            SetErrorNombre.setVisible(false);
//            SetErrorCedula.setVisible(false);
//            SetErrorCiudad1.setVisible(true);
//            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
//        }else if   ("".equals(Txt_Correo.getText()))
//        {
//            getToolkit().beep();
//            SetErrorDireccion.setVisible(false);
//            SetErrorCelular.setVisible(false);
//            SetErrorTelefono.setVisible(false);
//            SetErrorApellido.setVisible(false);
//            SetErrorNombre.setVisible(false);
//            SetErrorCedula.setVisible(false);
//            SetErrorCiudad1.setVisible(false);
//            SetErrorCorreo.setVisible(true);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
//        }
//        else
//        {
//            //Actualizar  Aspirante
//            CargarCargo ASP = (CargarCargo)Com_Cargo.getSelectedItem();
//            obj.setNombre(Txt_Nombre.getText());
//            obj.setApellido(Txt_Apellido.getText());
//            obj.setCedula (Txt_Identificacion1.getText());
//            obj.setCelular(Txt_TelefonoCelular1.getText());
//            obj.setTelefono(Txt_Telefono1.getText());
//            obj.setDireccion(Txt_Direccion.getText());
//            obj.setCiudad((String)Com_Ciudad.getSelectedItem());
//            obj.setCorreo(Txt_Correo.getText());
//            obj.setFechaPos(dateFormat.format(date));
//            obj.setCodigoCargo(ASP.getCodigoCargo());
//            obj.setDescripcion(Txt_Descripcion.getText());
//            obj.ActualizarTablas();
//            LimpiarTexBox();
//            NiconEvent Mensaje=new NiconEvent("Resultado del Registro","",NiconEvent.NOTIFY_OK,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ModificarActionPerformed
    }
    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed

        if (("".equals(Txt_Nombre.getText())))
        {
            getToolkit().beep();
            SetErrorNombre.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Nombre del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Apellido.getText()))
        {
            getToolkit().beep();
            SetErrorApellido.setVisible(true);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Apellido del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Identificacion1.getText()))
        {
            getToolkit().beep();
            SetErrorCedula.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Identificación del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);

        }
        else if   ("".equals(Txt_Telefono1.getText()))
        {
            getToolkit().beep();
            SetErrorTelefono.setVisible(true);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Telefono del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }
        else if   ("".equals(Txt_TelefonoCelular1.getText()))
        {
            getToolkit().beep();
            SetErrorCelular.setVisible(false);
            SetErrorTelefono.setVisible(true);
            SetErrorApellido.setVisible(true);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorDireccion.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Telefono Celular del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }
        else if   ("".equals(Txt_Direccion.getText()))
        {
            getToolkit().beep();
            SetErrorDireccion.setVisible(true);
            SetErrorCelular.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
//        }else if   ("--Seleccionar---".equals(Com_Ciudad.getSelectedItem()))
//        {
//            getToolkit().beep();
//            SetErrorDireccion.setVisible(false);
//            SetErrorCelular.setVisible(false);
//            SetErrorTelefono.setVisible(false);
//            SetErrorApellido.setVisible(false);
//            SetErrorNombre.setVisible(false);
//            SetErrorCedula.setVisible(false);
//            SetErrorCiudad1.setVisible(true);
//            SetErrorCorreo.setVisible(false);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }else if   ("".equals(Txt_Correo.getText()))
        {
            getToolkit().beep();
            SetErrorDireccion.setVisible(false);
            SetErrorCelular.setVisible(false);
            SetErrorTelefono.setVisible(false);
            SetErrorApellido.setVisible(false);
            SetErrorNombre.setVisible(false);
            SetErrorCedula.setVisible(false);
            SetErrorCiudad1.setVisible(false);
            SetErrorCorreo.setVisible(true);
//            SetErrorNota.setVisible(false);
//            NiconEvent Mensaje=new NiconEvent("Dato Requerido","Por Favor Ingrese el Direccion  del Aspirante",NiconEvent.NOTIFY_WARNING,0,0);
//            NotifyFactory.showDesktopNotify(Mensaje);
        }
        else
        {
            //Insertar Aspirante
//            CargarCargo ASP = (CargarCargo)Com_Cargo.getSelectedItem();
//            obj.setNombre(Txt_Nombre.getText());
//            obj.setApellido(Txt_Apellido.getText());
//            obj.setCedula (Txt_Identificacion1.getText());
//            obj.setCelular(Txt_TelefonoCelular1.getText());
//            obj.setTelefono(Txt_Telefono1.getText());
//            obj.setDireccion(Txt_Direccion.getText());
//            obj.setCiudad((String)Com_Ciudad.getSelectedItem());
//            obj.setCorreo(Txt_Correo.getText());
//            obj.InsertarAspirate();
//            //Insertar Postulaciones
//            obj.setFechaPos(dateFormat.format(date));
//            obj.setCodigoCargo(ASP.getCodigoCargo());
//            obj.InsertarPostulacion();
            //Insertar Proceso de seleccion
       //     obj.setDescripcion(Txt_Descripcion.getText());
           // obj.InsertPorsesoselecion();
            //Actualizamos el numero de vacantes
           // obj.ActualizarVacante(1);
           //// obj.TraerCodigos(Integer.parseInt(Txt_Identificacion1.getText()));
           // NiconEvent Mensaje=new NiconEvent("Resultado del Registro","Datos Guardados ",NiconEvent.NOTIFY_OK,0,0);
           // NotifyFactory.showDesktopNotify(Mensaje);
          //  setEnableContainer(JPanel_ProcesoSeleccion, true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_GuardarActionPerformed
    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
       // LimpiarTexBox();
    }//GEN-LAST:event_Btn_NuevoActionPerformed
    private void Btn_ContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ContratoActionPerformed
//        String Estado = "Contratado";
////        obj.setEstadoResultados(Estado);
// //       obj.InsertResultado();
//        Contrato Con = new Contrato();
//        Con. setVisible(true);
//        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ContratoActionPerformed

    private void Com_sucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Com_sucursalesActionPerformed
        // TODO add your handling code here:
        Cargarempleados();
    }//GEN-LAST:event_Com_sucursalesActionPerformed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void Txt_Direccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Direccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Direccion1ActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        //        this.Actualizar.setSelected(false);
        //        this.Buscar.setSelected(false);
        //        if (("".equals(this.Txt_Nombre.getText()) & "".equals(this.Txt_Apellido.getText())
            //            & "".equals(this.Txt_Direccion.getText()))) {
        //        setEnableContainer(JPanel_Contratacion, true);
        //        setEnableContainer(JPanel_Aspirante, true);
        //        setEnableContainer(JPanel_ProcesoSeleccion, false);
        //        this.Actualizar.setSelected(false);
        //        this.Btn_Guardar.setEnabled(true);
        //        this.Btn_Modificar.setEnabled(false);
        //        Btn_Contrato.setEnabled(false);
        //        }
        //        else
        //        {
            //            NiconEvent Mensaje=new NiconEvent("Error"," Para poder hacer un tienes que desocupar los campos  ",NiconEvent.NOTIFY_ERROR,0,0);
            //            NotifyFactory.showDesktopNotify(Mensaje);
            //            setEnableContainer( this.JPanel_Aspirante, false);
            //        }
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarActionPerformed

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nomina().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Contrato;
    private javax.swing.JButton Btn_Guardar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_Nuevo;
    private jcMousePanel.jcMousePanel Cerrar;
    private jcMousePanel.jcMousePanel Cerrar6;
    private jcMousePanel.jcMousePanel Cerrar7;
    public javax.swing.JComboBox Com_empleado;
    public javax.swing.JComboBox Com_sucursales;
    private javax.swing.JPanel DatosPersonales2;
    private javax.swing.JPanel DatosPersonales3;
    private javax.swing.JRadioButton Ingresar;
    private jcMousePanel.jcMousePanel JPanel_Aspirante;
    private javax.swing.JPanel JPanel_Contratacion;
    private jcMousePanel.jcMousePanel JPanel_ProcesoSeleccion;
    private javax.swing.JLabel Label4;
    private jcMousePanel.jcMousePanel Minimizar;
    private javax.swing.JLabel SetErrorApellido;
    private javax.swing.JLabel SetErrorCedula;
    private javax.swing.JLabel SetErrorCelular;
    private javax.swing.JLabel SetErrorCiudad1;
    private javax.swing.JLabel SetErrorCorreo;
    private javax.swing.JLabel SetErrorDireccion;
    private javax.swing.JLabel SetErrorNombre;
    private javax.swing.JLabel SetErrorNotaEntre;
    private javax.swing.JLabel SetErrorTelefono;
    public javax.swing.JTextField Txt_Apellido;
    public javax.swing.JTextField Txt_Correo;
    public javax.swing.JTextField Txt_Direccion;
    public javax.swing.JTextField Txt_Direccion1;
    public javax.swing.JFormattedTextField Txt_Identificacion1;
    public javax.swing.JTextField Txt_Nombre;
    public javax.swing.JFormattedTextField Txt_Telefono1;
    public javax.swing.JFormattedTextField Txt_TelefonoCelular1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables
}
