/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Miguel Angel
 */
public class SeccionVentas extends javax.swing.JFrame {

    /**
     * Creates new form SeccionVentas
     */
    public SeccionVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ApellidosEmpleado = new javax.swing.JLabel();
        NombreEmpleado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPanel_Noticias = new jcMousePanel.jcMousePanel();
        Btn_Evaluar8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jcMousePanel9 = new jcMousePanel.jcMousePanel();
        Btn_Evaluar1 = new javax.swing.JLabel();
        jcMousePanel10 = new jcMousePanel.jcMousePanel();
        Btn_Evaluar2 = new javax.swing.JLabel();
        jcMousePanel11 = new jcMousePanel.jcMousePanel();
        Btn_Evaluar3 = new javax.swing.JLabel();
        Lab_CerrarSesión = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Cerrar6 = new jcMousePanel.jcMousePanel();
        Minimizar = new jcMousePanel.jcMousePanel();
        Cerrar = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagene/Fondos/Abstract-Wallpaper-Fond-décran-de-leau-1920x2560.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        ApellidosEmpleado.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        ApellidosEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        ApellidosEmpleado.setText("Apellido Empleado");
        ApellidosEmpleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel1.add(ApellidosEmpleado);
        ApellidosEmpleado.setBounds(70, 30, 140, 20);

        NombreEmpleado.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        NombreEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpleado.setText("Nombre Empleado");
        NombreEmpleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        jPanel1.add(NombreEmpleado);
        NombreEmpleado.setBounds(70, 10, 140, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/48/user.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 50, 50);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(10, 10, 230, 70);

        JPanel_Noticias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Noticias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 14), java.awt.Color.white)); // NOI18N
        JPanel_Noticias.setModo(2);
        JPanel_Noticias.setVisibleLogo(false);
        JPanel_Noticias.setLayout(null);

        Btn_Evaluar8.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Btn_Evaluar8.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Evaluar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/add-user.png"))); // NOI18N
        Btn_Evaluar8.setText("Ventas Realizadas");
        Btn_Evaluar8.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Btn_Evaluar8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Evaluar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Evaluar8MouseClicked(evt);
            }
        });
        JPanel_Noticias.add(Btn_Evaluar8);
        Btn_Evaluar8.setBounds(10, 40, 190, 40);

        jPanel3.add(JPanel_Noticias);
        JPanel_Noticias.setBounds(20, 90, 220, 390);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 14), java.awt.Color.white)); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jcMousePanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facturas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 18), java.awt.Color.white)); // NOI18N
        jcMousePanel9.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/128/64/notes.png"))); // NOI18N
        jcMousePanel9.setModo(2);
        jcMousePanel9.setPosicionLogo(new java.awt.Point(30, 30));
        jcMousePanel9.setLayout(null);

        Btn_Evaluar1.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        Btn_Evaluar1.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Evaluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/edit-notes.png"))); // NOI18N
        Btn_Evaluar1.setText("Nueva Venta");
        Btn_Evaluar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Btn_Evaluar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Evaluar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Evaluar1MouseClicked(evt);
            }
        });
        jcMousePanel9.add(Btn_Evaluar1);
        Btn_Evaluar1.setBounds(100, 40, 140, 40);

        jPanel4.add(jcMousePanel9);
        jcMousePanel9.setBounds(20, 30, 290, 110);

        jcMousePanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 18), java.awt.Color.white)); // NOI18N
        jcMousePanel10.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/128/64/notes.png"))); // NOI18N
        jcMousePanel10.setModo(2);
        jcMousePanel10.setPosicionLogo(new java.awt.Point(30, 30));
        jcMousePanel10.setLayout(null);

        Btn_Evaluar2.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        Btn_Evaluar2.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Evaluar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/edit-notes.png"))); // NOI18N
        Btn_Evaluar2.setText("Solicitar Productos");
        Btn_Evaluar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Btn_Evaluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Evaluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Evaluar2MouseClicked(evt);
            }
        });
        jcMousePanel10.add(Btn_Evaluar2);
        Btn_Evaluar2.setBounds(110, 30, 170, 40);

        jPanel4.add(jcMousePanel10);
        jcMousePanel10.setBounds(20, 270, 290, 100);

        jcMousePanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cotisaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Euphemia", 0, 18), java.awt.Color.white)); // NOI18N
        jcMousePanel11.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/ImagenesMenu/128/64/notes.png"))); // NOI18N
        jcMousePanel11.setModo(2);
        jcMousePanel11.setPosicionLogo(new java.awt.Point(30, 30));
        jcMousePanel11.setLayout(null);

        Btn_Evaluar3.setFont(new java.awt.Font("Euphemia", 0, 14)); // NOI18N
        Btn_Evaluar3.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Evaluar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/edit-notes.png"))); // NOI18N
        Btn_Evaluar3.setText("Generar Cotisacion");
        Btn_Evaluar3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Btn_Evaluar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Evaluar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Evaluar3MouseClicked(evt);
            }
        });
        jcMousePanel11.add(Btn_Evaluar3);
        Btn_Evaluar3.setBounds(100, 40, 170, 40);

        jPanel4.add(jcMousePanel11);
        jcMousePanel11.setBounds(20, 150, 290, 110);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(250, 90, 340, 390);

        Lab_CerrarSesión.setFont(new java.awt.Font("Euphemia", 0, 12)); // NOI18N
        Lab_CerrarSesión.setForeground(new java.awt.Color(255, 255, 255));
        Lab_CerrarSesión.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/delete-user.png"))); // NOI18N
        Lab_CerrarSesión.setText("Cerrar Sesión");
        Lab_CerrarSesión.setToolTipText("");
        Lab_CerrarSesión.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        Lab_CerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lab_CerrarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lab_CerrarSesiónMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lab_CerrarSesiónMouseEntered(evt);
            }
        });
        jPanel3.add(Lab_CerrarSesión);
        Lab_CerrarSesión.setBounds(390, 0, 120, 40);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setOpaque(false);

        Cerrar6.setToolTipText("Ayuda");
        Cerrar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/faq.png"))); // NOI18N
        Cerrar6.setVisibleLogo(false);
        Cerrar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cerrar6Layout = new javax.swing.GroupLayout(Cerrar6);
        Cerrar6.setLayout(Cerrar6Layout);
        Cerrar6Layout.setHorizontalGroup(
            Cerrar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        Cerrar6Layout.setVerticalGroup(
            Cerrar6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Minimizar.setToolTipText("Minimizar");
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/download.png"))); // NOI18N
        Minimizar.setVisibleLogo(false);
        Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MinimizarLayout = new javax.swing.GroupLayout(Minimizar);
        Minimizar.setLayout(MinimizarLayout);
        MinimizarLayout.setHorizontalGroup(
            MinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        MinimizarLayout.setVerticalGroup(
            MinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Cerrar.setToolTipText("Cerrar");
        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/32/delete.png"))); // NOI18N
        Cerrar.setVisibleLogo(false);
        Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(510, 0, 90, 30);

        jcMousePanel1.add(jPanel3);
        jPanel3.setBounds(10, 10, 600, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Evaluar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Evaluar1MouseClicked
        FacturaVenta Venta = new FacturaVenta();
      Venta .setVisible(true); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Evaluar1MouseClicked

    private void Btn_Evaluar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Evaluar8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Evaluar8MouseClicked

    private void Btn_Evaluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Evaluar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Evaluar2MouseClicked

    private void Btn_Evaluar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Evaluar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Evaluar3MouseClicked

    private void Lab_CerrarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab_CerrarSesiónMouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Lab_CerrarSesiónMouseClicked

    private void Lab_CerrarSesiónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lab_CerrarSesiónMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Lab_CerrarSesiónMouseEntered

    private void Cerrar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cerrar6MouseClicked

    private void MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizarMouseClicked

    private void CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeccionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeccionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeccionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeccionVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeccionVentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidosEmpleado;
    private javax.swing.JLabel Btn_Evaluar1;
    private javax.swing.JLabel Btn_Evaluar2;
    private javax.swing.JLabel Btn_Evaluar3;
    private javax.swing.JLabel Btn_Evaluar8;
    private jcMousePanel.jcMousePanel Cerrar;
    private jcMousePanel.jcMousePanel Cerrar6;
    private jcMousePanel.jcMousePanel JPanel_Noticias;
    private javax.swing.JLabel Lab_CerrarSesión;
    private jcMousePanel.jcMousePanel Minimizar;
    private javax.swing.JLabel NombreEmpleado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel10;
    private jcMousePanel.jcMousePanel jcMousePanel11;
    private jcMousePanel.jcMousePanel jcMousePanel9;
    // End of variables declaration//GEN-END:variables
}
